### PR TITLE
Set fixed C++ standard (and fix compilation for C++17)

### PR DESCRIPTION
**Pull request by ltoenning**
Starting with GCC 11, the default C++ standard used is C++17. The CMake doesn't define a C++ standard so the compilation failed. To avoid such surprises with a compiler update it might be better to set a fixed standard.

If using C++17 is fine, it also seems that C++17 is incompatible using the increment operators on bools, which were deprecated earlier.

### CODE REVIEW

**Comment by robertosfield** [comment]
I'm closing this PR as there is no point in compiling as C++17 for an old utility like VirtutalPlanetBuilder.

**Comment by ryandesign** [comment]
I agree that some C++ standard should be specified. It builds fine for me in C++11 mode. C++11 mode or newer is required when using current versions of OpenSceneGraph and gdal.

I am not a developer of VPB, just the person who packages it for MacPorts, but I would not be in favor of imposing a greater C++ standard than required. That just unnecessarily forces users of older systems to install newer compilers.

**Comment by robertosfield** [comment]
Both OSG and VPB do not require modern versions of C++, this is deliberate choice, they are both legacy APIs that are being maintained for old applications, and need compatibility with old OS and applications that run on them.

**Comment by ryandesign** [comment]
Current versions of gdal require C++11 so anything that uses them, including OpenSceneGraph and VirtualPlanetBuilder, do too, otherwise you get an error:

```
In file included from src/vpb/DataSet.cpp:40:
In file included from /opt/local/include/gdal_priv.h:61:
In file included from /opt/local/include/gdal.h:45:
/opt/local/include/cpl_port.h:168:2: error: Must have C++11 or newer.
#error Must have C++11 or newer.
 ^
```

If you still support older pre-C++11 versions of gdal, then I agree you don't want to enforce the use of C++11.

However @ltoenning's point remains valid: Your code may not be compatible with newer C++ standards of the future, yet compilers will default to newer C++ standards over time. This can (did) make your code fail to compile. This is why it's better to specify which C++ standard your code is written to. But the situation is complicated by depending on other libraries which may change their C++ language requirements over time.

Knowing as we now do that current gdal requires C++11, you could check for this in your configuration process, e.g. try to compile something that includes gdal.h with `-std=c++98`. If it succeeds, you know you have an old gdal and you can compile your whole project with `-std=c++98`. If the test fails, try again with `-std=c++11`, and if that succeeds, use that for your whole build. This way you're protected from future incompatible C++ standards. However, I don't know how you could have anticipated that gdal would one day require C++11, and this suggestion doesn't help if some future version of gdal requires C++17 or newer. So I don't know what, if any, change should be made to VPB for this. Maybe nothing; maybe the user can be assumed to know how to resolve the error if they encounter it. Maybe a mention in your build instructions of the possible need to add a `-std` flag is enough.

**Comment by robertosfield** [comment]
Users can set their own compile flags via CMake so there is no need to put them into VPB CMakeLists.txt.  The only thing required is for VPB to compile with these configurations, and as far as I am aware VPB master compiles fine.

**Pull request closed without merging**
